#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
# fail exit if one of your pipe command fails
# exits if any of your variables is not set

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${ACCOUNTANT_DB_NAME}",
        user="${ACCOUNTANT_DB_USER}",
        password="${ACCOUNTANT_DB_PASSWORD}",
        host="${ACCOUNTANT_DB_HOST}",
        port="${ACCOUNTANT_DB_PORT}",
        sslmode="require",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
